### ISSUE TITLE
串接金流

### ISSUE THREAD

**Issue by chencac** [TourMind/tourmind#12]

**Comment by YuTingLan** [comment]
![截圖 2023-04-23 下午9 14 21](https://user-images.githubusercontent.com/127638342/234204064-58335dba-6701-46c7-bc2f-1030c81a35cc.png)

![截圖 2023-04-23 下午9 16 10](https://user-images.githubusercontent.com/127638342/234204151-68208114-aec5-42e6-955e-b777abfb01b0.png)

![截圖 2023-04-23 下午9 16 33](https://user-images.githubusercontent.com/127638342/234204319-c6f4fbcd-81c7-4a0f-8f24-9b6d27f07167.png)

![截圖 2023-04-23 下午9 17 23](https://user-images.githubusercontent.com/127638342/234204349-766715ce-5ded-4fd8-a64f-21fd5285f385.png)

授權成功 /  失敗
<img width="1427" alt="截圖 2023-04-24 上午9 32 33" src="https://user-images.githubusercontent.com/127638342/234211477-bf509125-ac92-4b1e-939d-7da25c5ed751.png">

<img width="1431" alt="截圖 2023-04-24 上午9 32 10" src="https://user-images.githubusercontent.com/127638342/234211491-30ccec88-c5f3-4378-8f43-4459a5f0677e.png">

付款成功靜態頁面
<img width="465" alt="截圖 2023-04-24 下午11 46 24" src="https://user-images.githubusercontent.com/127638342/234212199-d0f94811-edb3-4952-a2f6-44ff742c49c9.png">

**Comment by Hsubetty** [comment]
另外想問一下:
其他付款功能我們沒有做的話是否藍新的設定是可以刪除的？

**Comment by YuTingLan** [comment]
> 其他想問下: 其他付款功能我們沒有做的話是不是藍新的設置是可以刪除的？

不太明白你的意思？

目前會員制是一個月付款一次，會員到期後會取消會員，會員未到期不可再購買其他等級會員方案。你可以再註冊一個帳號測一下三個方案是不是都可已成功付款

如果你是問訂單的話，已經完成了，在等大家第一次合併完成後我會丟上去完整版！
（如果你想搶先測試可以先切到order的分支測試，那是完成版了，我只是尚未送PR）

會員付款方式是可以在做複雜一點，會做成如果尚未購買到最高等級紅鑽會員，可以補差價直接購買

但目前是以有功能，可付款，流程正常合理為主
目前想法因為我們並不販售行程規劃，所以這不是主要的功能？ 
所以就覺得精緻度可以放到最後票都做完了再來補（當然可以再討論唷～～～ 我現在都以簡單呈現無主）

**Comment by YuTingLan** [comment]
測試完成，已合併至dev
